# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Flatpak Verify

on:
  release:
    types: [published]
  push:
    tags:        
      - v*
    branches: [ master]
  pull_request:
    branches: [ master ]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        cat /etc/issue
        yum install -y p7zip p7zip-plugins
        7z
    # Docker is required by the docker/setup-qemu-action which enables emulation
    - name: Install deps
      run: |
        dnf -y install docker
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: wechat-devtools.flatpak
        manifest-path: io.github.msojocs.wechat-devtools.yml
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}